# Generated by Django 5.2.8 on 2025-11-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("MovieID", models.AutoField(primary_key=True, serialize=False)),
                ("MovieTitle", models.CharField(max_length=200)),
                ("Actor1Name", models.CharField(max_length=100)),
                ("Actor2Name", models.CharField(max_length=100)),
                ("DirectorName", models.CharField(max_length=100)),
                (
                    "MovieGenre",
                    models.CharField(
                        choices=[
                            ("Comedy", "Comedy"),
                            ("Romance", "Romance"),
                            ("Action", "Action"),
                            ("Drama", "Drama"),
                            ("Horror", "Horror"),
                            ("Sci-Fi", "Sci-Fi"),
                            ("Thriller", "Thriller"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ReleaseYear", models.IntegerField()),
            ],
            options={
                "db_table": "videos",
                "ordering": ["-ReleaseYear"],
            },
        ),
    ]
